spring:
  application:
    name: hexlet.code
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always

  springdoc:
    api-docs:
      enabled: true
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui.html

  sentry:
    dsn: ${{secrets.SENTRY_AUTH_TOKEN}}
    traces-sample-rate: 1.0