spring:
  application:
    name: hexlet.code
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always

  springdoc:
    api-docs:
      enabled: true
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui.html

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

sentry:
  dsn: ${{secrets.SENTRY_DNS}}
  traces-sample-rate: 1.0
