name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Delete Gradle Cache
        run: rm -rf ~/.gradle/caches

      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.5
          arguments: build --refresh-dependencies

      - name: Check Style
        run: ./gradlew checkstyleMain

      - name: Run Tests with Debug Logs
        run: ./gradlew test --info

      - name: Publish Code Coverage
        uses: paambaati/codeclimate-action@v6.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          JACOCO_SOURCE_PATH: src/main/java
        with:
          coverageCommand: make report
          coverageLocations: ${{ github.workspace }}/build/reports/jacoco/test/jacocoTestReport.xml:jacoco